spring.application.name=campus-ride

spring.datasource.url=jdbc:postgresql://localhost:5432/campus_ride
spring.datasource.username=campus_ride_app
spring.datasource.password=${CAMPUS_RIDE_DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.open-in-view=false